CREATE OR REPLACE VIEW COMPLETE_SALES_FULL_VIEW AS
SELECT
C.CUSTOMER_ID,
C.CUSTOMER_NAME,
C.PHONE AS CUSTOMER_PHONE,
C.EMAIL AS CUSTOMER_EMAIL,
C.ADDRESS AS CUSTOMER_ADDRESS,
C.CITY,
O.ORDER_ID,
O.CUSTOMER_ID AS ORDER_CUSTOMER_ID,
O.EMP_ID AS ORDER_EMPLOYEE_ID,
O.ORDER_DATE,
O.STATUS,
E.EMP_ID,
E.EMP_NAME,
E.DESIGNATION,
E.SALARY,
OI.ORDER_ITEM_ID,
OI.ORDER_ID AS ORDERITEM_ORDER_ID,
OI.PRODUCT_ID AS ORDER_PRODUCT_ID,
OI.QUANTITY AS ORDER_QUANTITY,
OI.PRICE AS ORDER_PRICE,
(OI.QUANTITY * OI.PRICE) AS TOTAL_PRICE,
P.PRODUCT_ID,
P.PRODUCT_NAME,
P.PRICE AS PRODUCT_PRICE,
P.STOCK,
P.CATEGORY_ID,
P.SUPPLIER_ID,
CAT.CATEGORY_NAME,
S.SUPPLIER_ID AS SUPPLIER_MASTER_ID,
S.SUPPLIER_NAME,
S.PHONE AS SUPPLIER_PHONE,
S.EMAIL AS SUPPLIER_EMAIL,
PAY.PAYMENT_ID,
PAY.ORDER_ID AS PAYMENT_ORDER_ID,
PAY.PAYMENT_MODE,
PAY.PAYMENT_DATE,
PAY.AMOUNT,
PU.PURCHASE_ID,
PU.PRODUCT_ID AS PURCHASE_PRODUCT_ID,
PU.SUPPLIER_ID AS PURCHASE_SUPPLIER_ID,
PU.QUANTITY AS PURCHASE_QUANTITY,
PU.PURCHASE_DATE,
I.LOG_ID,
I.PRODUCT_ID AS INVENTORY_PRODUCT_ID,
I.OLD_STOCK,
I.NEW_STOCK,
I.UPDATED_DATE
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN EMPLOYEES E
ON O.EMP_ID = E.EMP_ID
JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
JOIN CATEGORIES CAT
ON P.CATEGORY_ID = CAT.CATEGORY_ID
JOIN SUPPLIERS S
ON P.SUPPLIER_ID = S.SUPPLIER_ID
JOIN PAYMENTS PAY
ON O.ORDER_ID = PAY.ORDER_ID
JOIN PURCHASES PU
ON P.PRODUCT_ID = PU.PRODUCT_ID
AND S.SUPPLIER_ID = PU.SUPPLIER_ID
JOIN INVENTORY_LOG I
ON P.PRODUCT_ID = I.PRODUCT_ID;